### ISSUE TITLE
London OCIR does not work

### ISSUE THREAD

**Issue by alperozisik** [oracleimc/workshops#4]
If you use London region, docker cannot authenticate to that OCIR region for emeaccoe tenancy
`Error response from daemon: Get https://lhr.ocir.io/v2/: unknown: Tenant with namespace emeaccoe not found`

**Comment by allenkubai** [comment]
Use the Object Storage Namespace in place of the tenancy name. Therefore if you Object Storage Namespace is something like frxplqvlabxes then your username should be frxplqvlabxes/<username>.

The Object Storage Namespace can be found under your Adminstration>Tenancy Details.
